### ISSUE TITLE
How To Use

### ISSUE THREAD

**Issue by xiaoxidong** [MrMatthias/SwiftColorPicker#1]
HI,I am learning swift,but I kind of don't konw how to use this in a project,so can you tell me how to use it? or if there is an example would be great.Thank you so much.

**Comment by sixpolys** [comment]
Hi, i created an example on the example branch.
you can check it out within the SwiftColorPicker Repository with `git checkout example`
Feel free to ask further questions.

**Comment by xiaoxidong** [comment]
Thank you so much,it is a perfect solution for my app to choose a color,again,thank you.
