### ISSUE TITLE
Resize problems

### ISSUE THREAD

**Issue by dlmv** [MrMatthias/SwiftColorPicker#15]
I experienced some problems when using ColorPicker with storyboard and constraints. I managed to solve them, but not sure if it was a best way. So, either I can make a pull request, or you can fix by yourself.

1. Crash in `CFDataSetLength(mutableData, size)` in PickerImage.
I changed this line to
`mutableData = CFDataCreateMutable(kCFAllocatorDefault, size)`
and made all mutableData uses (`changeSize` and `writeColorData`) synchronized with a DispatchQueue.

2. ColorPicker and HuePicker store color data as absolute coordinates, which become wrong after resizing. I made coordinates to be relative, so that in ColorPicker x is exactly saturation and y is exactly brightness, while in HuePicker x is exactly hue.

**Comment by sixpolys** [comment]
That's indeed not implemented. Please make a pull request

**Comment by dlmv** [comment]
Seems like you can close this issue now. Btw, are you going to update the pod?
