### ISSUE TITLE
Crashes in iOS 11 due to nil CGDataProvider

### ISSUE THREAD

**Issue by lastmboy** [MrMatthias/SwiftColorPicker#24]
in PickerImage.swift, in createImageFromData, the line `imageSource = CGImageSourceCreateWithDataProvider(provider!, nil)` generates the `Unexpectedly found NULL when unwrapping a value` error. When following in debugger, the `provider` value created in the previous line is NULL.

After further research, the null provider is because iOS 11 rejects a zero length value for mutableData. Adding the following line in the init() fixed it for me.
`CFDataSetLength(mutableData, size)`

**Comment by matrejek** [comment]
I think it might be related with #12.
