### ISSUE TITLE
Repository branching, new version release

### ISSUE THREAD

**Issue by matrejek** [MrMatthias/SwiftColorPicker#25]
Hi @MrMatthias,
I am going to use SwiftColorPicker in my project and would like to support that project a bit. However, I would like to know what is the current policy related to repo branching? I see that currently the most active branch is example. I think it is well, as it follows common Pod structure and it is updated to current swift. I have also used it for a while and it looks quite stable. What do you think about merging these changes to master branch and releasing updated version of the library? 

I guess that we could fix #12  (and/or #24), merge the example branch and release nice, updated version then. 

I am eager to help you that as I find the library really helpful for me :) 

Regards,

Mateusz

**Comment by sixpolys** [comment]
Sounds good, I'll merge it as soon as possible.
Regards,
Matthias
