### ISSUE TITLE
Problem with constraints

### ISSUE THREAD

**Issue by xiaoxidong** [MrMatthias/SwiftColorPicker#5]
HI,Matthias
I want to use it both in iPhone and iPad,so I add some constraints to the colorWell,colorPicker and huePicker,but when I tap the huePicker,the colorPicker seems have something wrong,the color is NOT right,so do you have any idea how can I fix it? Thank you so much.

**Comment by sixpolys** [comment]
Hi, does the color not change or is it a different color? can you make a screenshot?

**Comment by xiaoxidong** [comment]
if you add some constraints,it will look like this.
![img_0641](https://cloud.githubusercontent.com/assets/3838258/7925580/0cde10f8-08f9-11e5-903e-fdf8275995e2.jpg)

**Comment by xiaoxidong** [comment]
HI,any probelm with this?

**Comment by sixpolys** [comment]
i wasn't able to reproduce the error with the example in the example branch yet. Do you use a storyboard or create the views in code? so far there is no code to handle changes in size.

**Comment by xiaoxidong** [comment]
Yes,I use a storyboard and add constraints in the storyboard,so any idea how can I fix this?

**Comment by sixpolys** [comment]
Can you upload the source somewhere so i can debug it? It looks  like it starts with a shorter width and then changes size and color

**Comment by xiaoxidong** [comment]
https://github.com/xiaoxidong/ColorPicker  Here is the code,thank you so much.

**Comment by sixpolys** [comment]
Hi, no problem, thanks for reporting the bug. It changes indeed the size. A quick fix would be to give it a constant size in storyboard until i add the code to handle size changes.

**Comment by sixpolys** [comment]
I pushed version 0.0.5 to cocoapods that should fix the bug

**Comment by xiaoxidong** [comment]
HI,how long will it take to release?it is still 0.0.4.

**Comment by sixpolys** [comment]
Hi, i released it 12 days ago. do you have 0.0.4 in your podfile? https://cocoapods.org/pods/SwiftColorPicker
