### ISSUE TITLE
It's a lot of error after I add SwiftColorPicker to pod file

### ISSUE THREAD

**Issue by hangkimduyen** [MrMatthias/SwiftColorPicker#7]
It's a lot of error after I add SwiftColorPicker to pod file
![screen shot 0028-02-19 at 10 49 17](https://cloud.githubusercontent.com/assets/12824282/13166121/bbe64a90-d6f6-11e5-9617-4b5f1f3f402e.png)

How can I fix them?

**Comment by sixpolys** [comment]
try to use the latest version. I comitted the changes for the latest xcode version today

**Comment by netbull** [comment]
Same thing here..
<img width="1916" alt="screen shot 2016-08-30 at 14 32 01" src="https://cloud.githubusercontent.com/assets/2797954/18087577/958886be-6ebe-11e6-87f7-8d3587a6d3e4.png">

**Comment by sixpolys** [comment]
I updated the Syntax to Swift 3.0
