### ISSUE TITLE
How to add white and Black Color in HuePicker

### ISSUE THREAD

**Issue by anitalanet** [MrMatthias/SwiftColorPicker#9]
Hi

I am using HuePicker class in my project but i want to add more mine selected color. How can i add please let me know

Help will be more approciated
Thanks in advance

**Comment by sixpolys** [comment]
Hi, you'd have to rewrite the translation between coordinates and colors in the input handling and rendering to add black and white into it

**Comment by anitalanet** [comment]
Hey.. Thanks for your reply. But the code written by you is little bit difficult. Can you please write the code for me ?
